skip_branch_with_pr: true

environment:
  matrix:
    - TOXENV: dist-
    - TOXENV: py35-pyqt5
    - TOXENV: py35-pyside2
    - TOXENV: py36-pyqt5
    - TOXENV: py36-pyside2
    - TOXENV: py37-pyqt5
    - TOXENV: py37-pyside2

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
  - echo "TOXENV- %TOXENV%"

install:
  - py -3.7 -m venv venv
  - venv\\Scripts\\activate
  - python -c "import sys; print(sys.version)"
  - pip install -r requirements.tox.txt
  - ps: Update-AppveyorBuild -Version "v$(python get_version.py) b$Env:APPVEYOR_BUILD_NUMBER"

build_script:
  - tox
  - tox -e codecov

artifacts:
  - path: "dist\\*"

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
