version: 2

job_template: &job_template
  steps:
    - checkout

    - run: &run_prepare
        name: Prepare
        command: |
          python3 --version
          python3 -m pip --version
          python3 -m pip install -q --user --ignore-installed --upgrade virtualenv
          python3 -m virtualenv venv
          venv/bin/python -m pip install --upgrade pip
          venv/bin/python -m pip freeze
          venv/bin/python --version
          venv/bin/pip --version
          venv/bin/pip install tox
    - run: &run_test
        name: Test
        command: |
          venv/bin/tox
          venv/bin/tox -e codecov

jobs:
  linux-py35:
    <<: *job_template
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV=py35

  linux-py36:
    <<: *job_template
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV=py36

  linux-py37:
    <<: *job_template
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV=py37

  osx-template: &osx-template
    <<: *job_template
    macos:
      xcode: "10.0.0"
    steps:
      - run:
          name: OSX Prepare
          command: |
            brew install readline xz pyenv
            python pyenvinstall.py
            echo 'export PATH=~/.pyenv/shims:$PATH' >> $BASH_ENV

  osx-py35:
    <<: *osx-template
    environment:
      TOXENV=py35

  osx-py36:
    <<: *osx-template
    environment:
      TOXENV=py36

  osx-py37:
    <<: *osx-template
    environment:
      TOXENV=py37

workflows:
  version: 2
  all:
    jobs:
      - linux-py35
      - linux-py36
      - linux-py37
      - osx-py35
      - osx-py36
      - osx-py37
